# 此 AWS SAM 模板是根据您的函数配置生成的。如果您的函数有一个或多个触发器，则请注意与这些触发器关联的 AWS 资源未在此模板中完全指定，并且 AWS
# 资源包含占位符值。在 AWS 基础架构编辑器或您最喜欢的 IDE 中打开此模板并对其进行修改，以指定具有其他 AWS 资源的无服务器应用程序。
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An AWS Serverless Application Model template describing your function.
Resources:
  lambda1:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src
      Description: ''
      MemorySize: 128
      Timeout: 3
      Handler: index.handler
      Runtime: nodejs22.x
      Architectures:
        - x86_64
      EphemeralStorage:
        Size: 512
      EventInvokeConfig:
        MaximumEventAgeInSeconds: 21600
        MaximumRetryAttempts: 2
      PackageType: Zip
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
              Resource: arn:aws:logs:ap-northeast-1:825765409936:*
            - Effect: Allow
              Action:
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource:
                - >-
                  arn:aws:logs:ap-northeast-1:825765409936:log-group:/aws/lambda/lambda1:*
      RecursiveLoop: Terminate
      SnapStart:
        ApplyOn: None
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /lambda1
            Method: ANY
      RuntimeManagementConfig:
        UpdateRuntimeOn: Auto
